# **00_SetUp**

In [ ]:
!pip install geopandas
!pip install osmnx

In [ ]:
import requests
import json
import time
import pandas as pd
import geopandas as gpd
import osmnx as ox
import numpy as np
import os

In [ ]:
root = '/content/gdrive/MyDrive/IaaC_MaCAD/Module 3/3S_Studio/A.Eye_Guiding App for Tourists/01_Data/JSON/GeoJsons'

# **01_URLs & Tags**

In [ ]:
#Placename
vienna='Vienna, 1010, Austria '

In [ ]:
#tags
wine_dine_tag={'amenity':['bar','pub', 'cafe', 'restaurant', 'fast_food','biergarten', 'food_court', 'ice_cream', 'arts_cemter', 'nightclub', 'brothel', 'casino', 'cinema', 'gambling', 'stripclub', 'swingerclub', 'theatre']}
leisure_tag= {'leisure':True}
shopping_tag={'shop': ['clothes','bags','jewelery', 'fashion_accessories', 'fabric', 'leather', 'shoes', 'watches', 'beauty', 'cosmetics', 'hairdresser', 'perfumery', 'tattoo', 'florist','chocolate', 'garden_centre', 'houseware', 'antiques', 'electronics', 'mobile_phones', 'candles', 'carpet' 'mall, boutique']} #for POI analysis
shop_tag={'shop':True} #for analysis
religion_tag={'amenity':'place_of_worship', 'religion':True}
tourism_tag={'tourism':True}

# **02_Analysis**

In [ ]:
wine_dine=ox.geometries.geometries_from_place(vienna, tags=wine_dine_tag)
leisure = ox.geometries.geometries_from_place(vienna, tags=leisure_tag)
shop = ox.geometries.geometries_from_place(vienna, tags=shop_tag)
tourism_ox=ox.geometries.geometries_from_place(vienna, tags=tourism_tag)

# religion_ox=ox.geometries.geometries_from_place(vienna, tags=religion_tag)

## Check POIs

In [ ]:
wine_dine['type']='wine_dine'
print(wine_dine.shape)
wine_dine.head(2)

(6143, 379)


addr:city addr:country addr:housenumber addr:postcode  \
element_type osmid                                                            
node         29801740      Wien           AT              130          1020   
             46823888      Wien           AT               38          1150   

                       addr:street     amenity       brand brand:wikidata  \
element_type osmid                                                          
node         29801740   Handelskai   fast_food  McDonald's         Q38076   
             46823888  Selzergasse  restaurant         NaN            NaN   

                      brand:wikipedia   cuisine  ... name:kr name:he rental  \
element_type osmid                               ...                          
node         29801740   en:McDonald's    burger  ...     NaN     NaN    NaN   
             46823888             NaN  regional  ...     NaN     NaN    NaN   

                      shelter_type disused:brand disused:opening_hours  \
element_type osmid                                                       
node         29801740          NaN           NaN                   NaN   
             46823888          NaN           NaN                   NaN   

                      disused:operator source:geometry ways       type  
element_type osmid                                                      
node         29801740              NaN             NaN  NaN  wine_dine  
             46823888              NaN             NaN  NaN  wine_dine  

[2 rows x 379 columns]

In [ ]:
leisure['type'] = 'leisure'
print(leisure.shape)
leisure.head(2)

(11818, 316)


source                   geometry barrier bicycle foot  \
element_type osmid                                                              
node         83453802     NaN  POINT (16.40419 48.27470)     NaN     NaN  NaN   
             254640433    NaN  POINT (16.31869 48.19869)     NaN     NaN  NaN   

                       highway addr:city addr:country addr:housenumber  \
element_type osmid                                                       
node         83453802      NaN       NaN          NaN              NaN   
             254640433     NaN      Wien           AT               65   

                       addr:postcode  ... name:he name:ka name:lt     type  \
element_type osmid                    ...                                    
node         83453802            NaN  ...     NaN     NaN     NaN  leisure   
             254640433          1150  ...     NaN     NaN     NaN  leisure   

                       name_1 esperanto meadow note:opening_hours  \
element_type osmid                                                  
node         83453802     NaN       NaN    NaN                NaN   
             254640433    NaN       NaN    NaN                NaN   

                       note:opening_hours:1 note:opening_hours:2  
element_type osmid                                                
node         83453802                   NaN                  NaN  
             254640433                  NaN                  NaN  

[2 rows x 316 columns]

In [ ]:
shop['type']='shop'
print(shop.shape)
shop.head(2)

(10593, 475)


addr:city addr:country addr:housenumber addr:postcode  \
element_type osmid                                                            
node         15079903      Wien           AT              180          1140   
             15080180      Wien           AT             130B          1140   

                               addr:street  atm       brand brand:wikidata  \
element_type osmid                                                           
node         15079903  Hütteldorfer Straße  yes    Eurospar      Q12309283   
             15080180  Hütteldorfer Straße  NaN  Billa Plus            NaN   

                      brand:wikipedia        name  ... shop:car_repair  \
element_type osmid                                 ...                   
node         15079903     da:Eurospar    Eurospar  ...             NaN   
             15080180        de:Billa  Billa Plus  ...             NaN   

                      source:geometry area changing_table:count  \
element_type osmid                                                
node         15079903             NaN  NaN                  NaN   
             15080180             NaN  NaN                  NaN   

                      disused:opening_hours disused:brand:wikidata  \
element_type osmid                                                   
node         15079903                   NaN                    NaN   
             15080180                   NaN                    NaN   

                      disused:brand:wikipedia recycling:batteries ways  \
element_type osmid                                                       
node         15079903                     NaN                 NaN  NaN   
             15080180                     NaN                 NaN  NaN   

                      loc_name  
element_type osmid              
node         15079903      NaN  
             15080180      NaN  

[2 rows x 475 columns]

In [ ]:
tourism_ox['type']='tourism'
print(tourism_ox.shape)
tourism_ox.head(2)

(3052, 370)


barrier foot                   geometry highway  \
element_type osmid                                                      
node         60438337     NaN  NaN  POINT (16.36826 48.20464)     NaN   
             60571580     NaN  NaN  POINT (16.33669 48.27439)     NaN   

                      addr:city addr:country addr:housenumber addr:postcode  \
element_type osmid                                                            
node         60438337      Wien           AT                1          1010   
             60571580       NaN          NaN              NaN           NaN   

                          addr:street      amenity  ... government  \
element_type osmid                                  ...              
node         60438337  Albertinaplatz  arts_centre  ...        NaN   
             60571580             NaN          NaN  ...        NaN   

                      building:start_date name:restaurant castle_type:fr  \
element_type osmid                                                         
node         60438337                 NaN             NaN            NaN   
             60571580                 NaN             NaN            NaN   

                      castle_type:it is_in:theme_park old_name:en  \
element_type osmid                                                  
node         60438337            NaN              NaN         NaN   
             60571580            NaN              NaN         NaN   

                      breakfast:buffet language:de language:en  
element_type osmid                                              
node         60438337              NaN         NaN         NaN  
             60571580              NaN         NaN         NaN  

[2 rows x 370 columns]

In [ ]:
# religion_ox['type'] = 'religion'
# print(religion_ox.shape)
# religion_ox.head(2)

## Merge

In [ ]:
merged_list=pd.concat([wine_dine, leisure, shop, tourism_ox])

In [ ]:
reduced = merged_list.drop_duplicates(subset=['name'], keep='first')

In [ ]:
print(merged_list.shape)
print(reduced.shape)

(31606, 901)
(15156, 901)


In [ ]:
reduced.head(5)

addr:city addr:country addr:housenumber addr:postcode  \
element_type osmid                                                            
node         29801740      Wien           AT              130          1020   
             46823888      Wien           AT               38          1150   
             46823910      Wien           AT               13          1150   
             46823914      Wien           AT               11          1150   
             46823918       NaN          NaN              NaN           NaN   

                        addr:street     amenity       brand brand:wikidata  \
element_type osmid                                                           
node         29801740    Handelskai   fast_food  McDonald's         Q38076   
             46823888   Selzergasse  restaurant         NaN            NaN   
             46823910  Meiselstraße  restaurant         NaN            NaN   
             46823914  Meiselstraße        cafe         NaN            NaN   
             46823918           NaN   fast_food         NaN            NaN   

                      brand:wikipedia   cuisine  ... townhall:type  \
element_type osmid                               ...                 
node         29801740   en:McDonald's    burger  ...           NaN   
             46823888             NaN  regional  ...           NaN   
             46823910             NaN     pizza  ...           NaN   
             46823914             NaN       NaN  ...           NaN   
             46823918             NaN     asian  ...           NaN   

                      building:start_date name:restaurant castle_type:fr  \
element_type osmid                                                         
node         29801740                 NaN             NaN            NaN   
             46823888                 NaN             NaN            NaN   
             46823910                 NaN             NaN            NaN   
             46823914                 NaN             NaN            NaN   
             46823918                 NaN             NaN            NaN   

                      castle_type:it is_in:theme_park old_name:en  \
element_type osmid                                                  
node         29801740            NaN              NaN         NaN   
             46823888            NaN              NaN         NaN   
             46823910            NaN              NaN         NaN   
             46823914            NaN              NaN         NaN   
             46823918            NaN              NaN         NaN   

                      breakfast:buffet language:de language:en  
element_type osmid                                              
node         29801740              NaN         NaN         NaN  
             46823888              NaN         NaN         NaN  
             46823910              NaN         NaN         NaN  
             46823914              NaN         NaN         NaN  
             46823918              NaN         NaN         NaN  

[5 rows x 901 columns]

In [ ]:
reduced.columns.values

array(['addr:city', 'addr:country', 'addr:housenumber', 'addr:postcode',
       'addr:street', 'amenity', 'brand', 'brand:wikidata',
       'brand:wikipedia', 'cuisine', 'name', 'opening_hours', 'takeaway',
       'toilets:wheelchair', 'wheelchair', 'geometry', 'contact:website',
       'indoor_seating', 'outdoor_seating', 'phone', 'website',
       'diet:vegetarian', 'smoking', 'cinema:3D', 'level', 'payment:cash',
       'payment:credit_cards', 'payment:maestro', 'screen', 'wikidata',
       'wikipedia', 'name:en', 'operator', 'wheelchair:description',
       'alt_name', 'note', 'short_name', 'closed', 'delivery', 'shop',
       'source', 'fax', 'fixme', 'changing_table', 'email',
       'internet_access', 'microbrewery', 'name:ru', 'name:zh', 'brewery',
       'contact:email', 'contact:phone', 'internet_access:fee',
       'description', 'created_by', 'name:de', 'contact:facebook',
       'description:covid19', 'opening_hours:covid19', 'sport',
       'addr:unit', 'description:en', 

In [ ]:
osm_poi = reduced.loc[:, [ 'name', 'addr:street', 'amenity', 'leisure', 'shop', 'tourism', 'geometry']]
osm_poi.head()

name   addr:street     amenity leisure  \
element_type osmid                                                              
node         29801740            McDonald's    Handelskai   fast_food     NaN   
             46823888   Heidingers Gasthaus   Selzergasse  restaurant     NaN   
             46823910    Pizzeria Ramazotti  Meiselstraße  restaurant     NaN   
             46823914  Meiselmarkt Cafe-Pub  Meiselstraße        cafe     NaN   
             46823918         Lucky Noodles           NaN   fast_food     NaN   

                      shop tourism                   geometry  
element_type osmid                                             
node         29801740  NaN     NaN  POINT (16.39496 48.23346)  
             46823888  NaN     NaN  POINT (16.32300 48.19823)  
             46823910  NaN     NaN  POINT (16.32054 48.19748)  
             46823914  NaN     NaN  POINT (16.32087 48.19746)  
             46823918  NaN     NaN  POINT (16.32126 48.19753)

## Classify

Identify different classes in OSM data

### Gender

#### Gay locations

In [ ]:
g=[]
for j in reduced.columns.values:
  if ('gay' in j) | ('gay:men' in j) | ('gay:women' in j) | ('gay:transgender' in j) | ('fetish:leather' in j):
    v=reduced[j].str.contains('yes|primary|welcome|only', regex=True, na=False)
    g.append(v)
l=np.sum(g,axis=0)
print(l)
l.shape


[0 0 0 ... 0 0 0]


(15156,)

In [ ]:
osm_poi['lgbtq_friendly'] = l>=1
lgbtq_friendly=osm_poi[osm_poi['lgbtq_friendly']==True].loc[:,'name':'tourism']
print(lgbtq_friendly.shape)
osm_poi.head(2)

(20, 6)


name  addr:street     amenity leisure  \
element_type osmid                                                            
node         29801740           McDonald's   Handelskai   fast_food     NaN   
             46823888  Heidingers Gasthaus  Selzergasse  restaurant     NaN   

                      shop tourism                   geometry  lgbtq_friendly  
element_type osmid                                                             
node         29801740  NaN     NaN  POINT (16.39496 48.23346)           False  
             46823888  NaN     NaN  POINT (16.32300 48.19823)           False

#### Male

In [ ]:
g=[]
for j in reduced.columns.values:
  if ('male' in j) | ('gay:men' in j) | ('unisex' in j):
    v=reduced[j].str.contains('yes|primary|welcome|only|male', regex=True, na=False)
    g.append(v)
v = [True if (i=='male') else False for i in reduced.access.values]
g.append(v)
v= [True if (i=='barber') else False for i in reduced.shop.values]
g.append(v)
m=np.sum(g,axis=0)
print(l)
m.shape

[0 0 0 ... 0 0 0]


(15156,)

In [ ]:
osm_poi['men_friendly'] = m>=1
men_friendly=osm_poi[osm_poi['men_friendly']==True].loc[:,'name':'tourism']
print(men_friendly.shape)
osm_poi.head(2)

(19, 6)


name  addr:street     amenity leisure  \
element_type osmid                                                            
node         29801740           McDonald's   Handelskai   fast_food     NaN   
             46823888  Heidingers Gasthaus  Selzergasse  restaurant     NaN   

                      shop tourism                   geometry  lgbtq_friendly  \
element_type osmid                                                              
node         29801740  NaN     NaN  POINT (16.39496 48.23346)           False   
             46823888  NaN     NaN  POINT (16.32300 48.19823)           False   

                       men_friendly  
element_type osmid                   
node         29801740         False  
             46823888         False

#### Female

In [ ]:
g=[]
for j in reduced.columns.values:
  if ('women' in j) | ('gay:women' in j) | ('female' in j) | ('unisex' in j) :
    v=reduced[j].str.contains('yes|primary|welcome|only|female', regex=True, na=False)
    g.append(v)
v = [True if (i=='hairdresser') else False for i in reduced.shop.values]
b = [True if i=='female' else False for i in reduced.access.values]
g.append(v)
g.append(b)
f=np.sum(g,axis=0)
print(l)
f.shape

[0 0 0 ... 0 0 0]


(15156,)

In [ ]:
osm_poi['women_friendly'] = f>=1
women_friendly=osm_poi[osm_poi['women_friendly']==True].loc[:,'name':'tourism']
print(women_friendly.shape)
osm_poi.head(2)

(776, 6)


name  addr:street     amenity leisure  \
element_type osmid                                                            
node         29801740           McDonald's   Handelskai   fast_food     NaN   
             46823888  Heidingers Gasthaus  Selzergasse  restaurant     NaN   

                      shop tourism                   geometry  lgbtq_friendly  \
element_type osmid                                                              
node         29801740  NaN     NaN  POINT (16.39496 48.23346)           False   
             46823888  NaN     NaN  POINT (16.32300 48.19823)           False   

                       men_friendly  women_friendly  
element_type osmid                                   
node         29801740         False           False  
             46823888         False           False

### Ethnicity

In [ ]:
ethnicity = reduced.loc[:, ['name', 'description', 'cuisine','brand','amenity', 'leisure', 'shop']]
ethnicity.head()

name description   cuisine       brand  \
element_type osmid                                                              
node         29801740            McDonald's         NaN    burger  McDonald's   
             46823888   Heidingers Gasthaus         NaN  regional         NaN   
             46823910    Pizzeria Ramazotti         NaN     pizza         NaN   
             46823914  Meiselmarkt Cafe-Pub         NaN       NaN         NaN   
             46823918         Lucky Noodles         NaN     asian         NaN   

                          amenity leisure shop  
element_type osmid                              
node         29801740   fast_food     NaN  NaN  
             46823888  restaurant     NaN  NaN  
             46823910  restaurant     NaN  NaN  
             46823914        cafe     NaN  NaN  
             46823918   fast_food     NaN  NaN

#### Afro_carribean

In [ ]:
african =['african','carribean']
e=[]
for j in reduced.columns.values:
  if ('afrika' in j) | ('Afrika' in j) | ('africa' in j) | ('africa' in j) | ('carribean' in j) | ('jamaica' in j) | ('couscous' in j):
    v = reduced[j].astype(str).str.contains('yes|only', case=False, regex=True, na=False) 
  else:
    v = reduced[j].astype(str).str.contains('africa|afrika|african|couscous|carribean|jollof|fried_rice|fufu|banku|waakye|afro|braids|nigeria|libya|ethiopia|jamaica|ghana|senegalese|maroc|calabash|egypt|amala', case=False, regex=True, na=False)
  e.append(v)
af=np.sum(e,axis=0)
print(l)
af.shape


[0 0 0 ... 0 0 0]


(15156,)

In [ ]:
osm_poi['afro_carribean'] = af>=1
afro_friendly=osm_poi[osm_poi['afro_carribean']==True].loc[:,'name':'tourism']
print(afro_friendly.shape)
osm_poi.head(2)
afro_friendly.head()

(25, 6)


name        addr:street  \
element_type osmid                                                       
node         425488870                  Le Couscous  Bösendorferstraße   
             1207358918         Jamaica Beach (FKK)                NaN   
             1210670891                      Kamala      Hollandstraße   
             1291414393                 Petit Maroc        Neubaugasse   
             1668100065  Rachel's African Sensation          Ennsgasse   

                            amenity leisure shop tourism  
element_type osmid                                        
node         425488870   restaurant     NaN  NaN     NaN  
             1207358918  restaurant     NaN  NaN     NaN  
             1210670891  restaurant     NaN  NaN     NaN  
             1291414393  restaurant     NaN  NaN     NaN  
             1668100065   fast_food     NaN  NaN     NaN

#### Asian

In [ ]:
asi=[]

for j in reduced.columns.values:
  if ('sushi' in j) | ('noodles' in j) | ('kimchi' in j) | ('oriental' in j):
    v = reduced[j].astype(str).str.contains('yes', case=False, regex=True, na=False) 
  else:
    v = reduced[j].astype(str).str.contains('asian|chinese|japanese|thai|sushi|vietnamese|korea|kimchi|dumplings|noodles|ramen', case=False, regex=True, na=False)
  asi.append(v)
asi=np.sum(asi,axis=0)
print(asi)
asi.shape


[0 0 0 ... 0 0 0]


(15156,)

In [ ]:
osm_poi['asian'] = asi>=1
asian_friendly=osm_poi[osm_poi['asian']==True].loc[:,'name':'tourism']
print(asian_friendly.shape)
osm_poi.head(2)

(534, 6)


name  addr:street     amenity leisure  \
element_type osmid                                                            
node         29801740           McDonald's   Handelskai   fast_food     NaN   
             46823888  Heidingers Gasthaus  Selzergasse  restaurant     NaN   

                      shop tourism                   geometry  lgbtq_friendly  \
element_type osmid                                                              
node         29801740  NaN     NaN  POINT (16.39496 48.23346)           False   
             46823888  NaN     NaN  POINT (16.32300 48.19823)           False   

                       men_friendly  women_friendly  afro_carribean  asian  
element_type osmid                                                          
node         29801740         False           False           False  False  
             46823888         False           False           False  False

#### Middle_eastern

In [ ]:
me=[]

for j in reduced.columns.values:
  if ('halal' in j) | ('ramadan' in j) | ('persian' in j) | ('lebanese' in j):
    v = reduced[j].astype(str).str.contains('yes', case=False, regex=True, na=False)
  else:
    v = reduced[j].astype(str).str.contains('arab|halal|Qatar|dubai|saudi|hijab|ramadan|persian|iraq|afghan|lebanese|egypt|maroc|algeria|syria', case=False, regex=True, na=False)
  me.append(v)
me=np.sum(me,axis=0)
print(me)
me.shape


[0 0 0 ... 0 0 0]


(15156,)

In [ ]:
osm_poi['mid_east'] = me>=1
mid_east_friendly=osm_poi[osm_poi['mid_east']==True].loc[:,'name':'tourism']
print(mid_east_friendly.shape)
osm_poi.head(2)

(53, 6)


name  addr:street     amenity leisure  \
element_type osmid                                                            
node         29801740           McDonald's   Handelskai   fast_food     NaN   
             46823888  Heidingers Gasthaus  Selzergasse  restaurant     NaN   

                      shop tourism                   geometry  lgbtq_friendly  \
element_type osmid                                                              
node         29801740  NaN     NaN  POINT (16.39496 48.23346)           False   
             46823888  NaN     NaN  POINT (16.32300 48.19823)           False   

                       men_friendly  women_friendly  afro_carribean  asian  \
element_type osmid                                                           
node         29801740         False           False           False  False   
             46823888         False           False           False  False   

                       mid_east  
element_type osmid               
node         29801740     False  
             46823888     False

#### South Asian

In [ ]:
ind=[]

for j in reduced.columns.values:
  if ('india' in j) | ('curry' in j) | ('hindu' in j):
    v = reduced[j].astype(str).str.contains('yes', case=False, regex=True, na=False)
  else:
    v = reduced[j].astype(str).str.contains('indian|hindu|pakistan|sri lanka|kebab|curry', case=False, regex=True, na=False)
  ind.append(v)
ind=np.sum(ind,axis=0)
print(ind)
ind.shape


[0 0 0 ... 0 0 0]


(15156,)

In [ ]:
osm_poi['south_asian'] = ind>=1
south_asian_friendly=osm_poi[osm_poi['south_asian']==True].loc[:,'name':'tourism']
print(south_asian_friendly.shape)
osm_poi.head(2)

(253, 6)


name  addr:street     amenity leisure  \
element_type osmid                                                            
node         29801740           McDonald's   Handelskai   fast_food     NaN   
             46823888  Heidingers Gasthaus  Selzergasse  restaurant     NaN   

                      shop tourism                   geometry  lgbtq_friendly  \
element_type osmid                                                              
node         29801740  NaN     NaN  POINT (16.39496 48.23346)           False   
             46823888  NaN     NaN  POINT (16.32300 48.19823)           False   

                       men_friendly  women_friendly  afro_carribean  asian  \
element_type osmid                                                           
node         29801740         False           False           False  False   
             46823888         False           False           False  False   

                       mid_east  south_asian  
element_type osmid                            
node         29801740     False        False  
             46823888     False        False

#### Latinx

In [ ]:
lat=[]

for j in reduced.columns.values:
  v = reduced[j].astype(str).str.contains('latino|mexican|ecuador|latin_american|south america|argentina|brazil|barbados|peru|taco|empanada|churro|bolivian|capixaba', case=False, regex=True, na=False)
  lat.append(v)
lat=np.sum(lat,axis=0)
print(lat)
lat.shape

[0 0 0 ... 0 0 0]


(15156,)

In [ ]:
osm_poi['latinx'] = lat>=1
latinx_friendly=osm_poi[osm_poi['latinx']==True].loc[:,'name':'tourism']
print(latinx_friendly.shape)
osm_poi.head(2)

(41, 6)


name  addr:street     amenity leisure  \
element_type osmid                                                            
node         29801740           McDonald's   Handelskai   fast_food     NaN   
             46823888  Heidingers Gasthaus  Selzergasse  restaurant     NaN   

                      shop tourism                   geometry  lgbtq_friendly  \
element_type osmid                                                              
node         29801740  NaN     NaN  POINT (16.39496 48.23346)           False   
             46823888  NaN     NaN  POINT (16.32300 48.19823)           False   

                       men_friendly  women_friendly  afro_carribean  asian  \
element_type osmid                                                           
node         29801740         False           False           False  False   
             46823888         False           False           False  False   

                       mid_east  south_asian  latinx  
element_type osmid                                    
node         29801740     False        False   False  
             46823888     False        False   False

### Age

#### kids

In [ ]:
g=[]
for j in reduced.columns.values:
  if ('kids' in j):
    v=reduced[j].str.contains('yes|primary|welcome|only|male', regex=True, na=False)
    g.append(v)
g.append(v)
l=np.sum(g,axis=0)
print(l)
l.shape

[0 0 0 ... 0 0 0]


(15156,)

In [ ]:
osm_poi['kid_friendly'] = l>=1
kid_friendly=osm_poi[osm_poi['kid_friendly']==True].loc[:,'name':'tourism']
print(kid_friendly.shape)
osm_poi.head(2)

(1, 6)


name  addr:street     amenity leisure  \
element_type osmid                                                            
node         29801740           McDonald's   Handelskai   fast_food     NaN   
             46823888  Heidingers Gasthaus  Selzergasse  restaurant     NaN   

                      shop tourism                   geometry  lgbtq_friendly  \
element_type osmid                                                              
node         29801740  NaN     NaN  POINT (16.39496 48.23346)           False   
             46823888  NaN     NaN  POINT (16.32300 48.19823)           False   

                       men_friendly  women_friendly  afro_carribean  asian  \
element_type osmid                                                           
node         29801740         False           False           False  False   
             46823888         False           False           False  False   

                       mid_east  south_asian  latinx  kid_friendly  
element_type osmid                                                  
node         29801740     False        False   False         False  
             46823888     False        False   False         False

### Religion

#### Muslim_Friendly

In [ ]:
g=[]

for j in reduced.columns.values:
  if ('halal' in j):
    v= reduced[j].astype(str).str.contains('yes|only', case=False, regex=True, na=False)
  else:
    v = reduced[j].astype(str).str.contains('halal|islam|muslim|turk', case=False, regex=True, na=False)
  g.append(v)
ms=np.sum(g,axis=0)
print(ms)
ms.shape

[0 0 0 ... 0 0 0]


(15156,)

In [ ]:
osm_poi['muslim_friendly'] = ms>=1
muslim_friendly=osm_poi[osm_poi['muslim_friendly']==True].loc[:,'name':'tourism']
print(muslim_friendly.shape)
osm_poi.head(2)
muslim_friendly.head()

(107, 6)


name           addr:street  \
element_type osmid                                                         
node         244496431                   うまみ Umami  Lerchenfelder Straße   
             245495351                        Kent          Brunnengasse   
             256669740            Café Erdgeschoss     Schottenfeldgasse   
             295563589  Meksan Kebab und Grillhaus      Währinger Straße   
             298347612                  Kebap-Haus         Faulmanngasse   

                           amenity leisure shop tourism  
element_type osmid                                       
node         244496431  restaurant     NaN  NaN     NaN  
             245495351  restaurant     NaN  NaN     NaN  
             256669740        cafe     NaN  NaN     NaN  
             295563589  restaurant     NaN  NaN     NaN  
             298347612  restaurant     NaN  NaN     NaN

#### Jewish

In [ ]:
g=[]

for j in reduced.columns.values:
  if ('hummus' in j) | ('kosher' in j) | ('humus' in j):
    v= reduced[j].astype(str).str.contains('yes|only', case=False, regex=True, na=False)
  else:
    v = reduced[j].astype(str).str.contains('jewish|kosher|hummus|humus', case=False, regex=True, na=False)
  g.append(v)
jw=np.sum(g,axis=0)
jw.shape

(15156,)

In [ ]:
osm_poi['jewish'] = jw>=1
jewish_friendly=osm_poi[osm_poi['jewish']==True].loc[:,'name':'tourism']
print(jewish_friendly.shape)
osm_poi.head(2)
jewish_friendly.head()

(14, 6)


name     addr:street     amenity  \
element_type osmid                                                           
node         478928080                  Miznon   Schulerstraße  restaurant   
             1202223902              Alef Alef             NaN  restaurant   
             1715947090  Novellino kosher food     Zirkusgasse  restaurant   
             3961438009           Café Eskeles  Dorotheergasse        cafe   
             6826725636             Marktbeisl  Schwendermarkt  restaurant   

                        leisure shop tourism  
element_type osmid                            
node         478928080      NaN  NaN     NaN  
             1202223902     NaN  NaN     NaN  
             1715947090     NaN  NaN     NaN  
             3961438009     NaN  NaN     NaN  
             6826725636     NaN  NaN     NaN

#### Buddhist_friendly

In [ ]:
g=[]
for j in reduced.columns.values:
  if ('vegan' in j) | ('vegetarian' in j) | ('lacto_vegetarian' in j):
    v= reduced[j].astype(str).str.contains('yes|only', case=False, regex=True, na=False)
  else:
    v = reduced[j].astype(str).str.contains('vegan|vegetarian', case=False, regex=True, na=False)
  g.append(v)
bd=np.sum(g,axis=0)
bd.shape

(15156,)

In [ ]:
osm_poi['buddhist'] = bd>=1
buddhist_friendly=osm_poi[osm_poi['buddhist']==True].loc[:,'name':'tourism']
print(buddhist_friendly.shape)
osm_poi.head(2)
buddhist_friendly.head()

(560, 6)


name              addr:street  \
element_type osmid                                                              
node         60648368                      Phönixhof                      NaN   
             76514684                     Pizza Bizi          Rotenturmstraße   
             115212652                        Hitomi  Landstraßer Hauptstraße   
             115513011                          Aida  Landstraßer Hauptstraße   
             146317846  Kaffee-Konditorei Mayerhofer                      NaN   

                           amenity leisure shop tourism  
element_type osmid                                       
node         60648368   restaurant     NaN  NaN     NaN  
             76514684   restaurant     NaN  NaN     NaN  
             115212652   fast_food     NaN  NaN     NaN  
             115513011        cafe     NaN  NaN     NaN  
             146317846        cafe     NaN  NaN     NaN

## Filter Data and Export Geojson

In [ ]:
recreational =osm_poi[(osm_poi['type']=='wine_dine') | (osm_poi['type']=='leisure')]
recreational = recreational.dropna(axis=1, how='all')
print(recreational.shape)
recreational.head()

(6801, 22)


name   addr:street       type  \
element_type osmid                                                     
node         29801740            McDonald's    Handelskai  wine_dine   
             46823888   Heidingers Gasthaus   Selzergasse  wine_dine   
             46823910    Pizzeria Ramazotti  Meiselstraße  wine_dine   
             46823914  Meiselmarkt Cafe-Pub  Meiselstraße  wine_dine   
             46823918         Lucky Noodles           NaN  wine_dine   

                          amenity leisure shop tourism   cuisine  \
element_type osmid                                                 
node         29801740   fast_food     NaN  NaN     NaN    burger   
             46823888  restaurant     NaN  NaN     NaN  regional   
             46823910  restaurant     NaN  NaN     NaN     pizza   
             46823914        cafe     NaN  NaN     NaN       NaN   
             46823918   fast_food     NaN  NaN     NaN     asian   

                                        geometry  lgbtq_friendly  ...  \
element_type osmid                                                ...   
node         29801740  POINT (16.39496 48.23346)           False  ...   
             46823888  POINT (16.32300 48.19823)           False  ...   
             46823910  POINT (16.32054 48.19748)           False  ...   
             46823914  POINT (16.32087 48.19746)           False  ...   
             46823918  POINT (16.32126 48.19753)           False  ...   

                       afro_carribean  asian  mid_east  south_asian  latinx  \
element_type osmid                                                            
node         29801740           False  False     False        False   False   
             46823888           False  False     False        False   False   
             46823910           False  False     False        False   False   
             46823914           False  False     False        False   False   
             46823918           False   True     False        False   False   

                       european  muslim_friendly  jewish  buddhist  wheelchair  
element_type osmid                                                              
node         29801740      True             True   False     False       False  
             46823888      True            False   False     False       False  
             46823910      True             True   False     False       False  
             46823914      True            False   False     False       False  
             46823918     False            False   False     False       False  

[5 rows x 22 columns]

In [ ]:
path = root + 'poi'
recreational.to_file(path, driver='GeoJSON')